### ISSUE TITLE
undefined method `processor' for #<Team:0x007fc8fb7a3a48>

### ISSUE THREAD

**Issue by deep0389** [jasoncharnes/pay#48]
I added include Pay::Billable to my Team model.
When trying to process the payment I get
`undefined method `processor' for Team`

**Comment by jespr** [comment]
@deep0389 That's because your `teams` table in the database are missing the columns that this migration adds: https://github.com/jasoncharnes/pay/blob/master/db/migrate/20170503131610_add_fields_to_users.rb

So if you create an initializer: `config/initializers/pay.rb` with the following:

```
Pay.setup do |config|
  config.billable_class = 'Team'
end
```

If you set that, and run the Pay migrations again, the necessary fields should be added from the migration

**Comment by deep0389** [comment]
thanks for replying @jespr 
I have created those migrations. And I did run rails db:migrate.
Upon inspecting I found subscriptions table is created but columns are not added to teams table. Neither I see them in db/schema.rb

I tried switching migration version from 4.2 to 5.2 (since I am using rails 5) still team migration did not run.

**Comment by deep0389** [comment]
Fixed after deleting migrations and running again. weird issue.

**Comment by excid3** [comment]
Hmm, yeah that is weird. We'll have to keep an eye out for that.
